/* Portfolio data — placeholder content (lorem ipsum) */

/* Field hubs — large nodes that projects orbit around */
window.PROJECT_FIELDS = [
  { id: "ml", label: "ML", color: "#00f5ff", angle: -Math.PI * 0.5 },
  { id: "web", label: "Web", color: "#9d00ff", angle: -Math.PI * 0.166 },
  { id: "agentic", label: "Agentic", color: "#5eead4", angle: Math.PI * 0.166 },
  { id: "cyber", label: "Cyber", color: "#ff2bd6", angle: Math.PI * 0.5 },
  { id: "devops", label: "DevOps", color: "#ffc857", angle: Math.PI * 0.833 },
  { id: "cloud", label: "Cloud", color: "#7dd3fc", angle: -Math.PI * 0.833 },
];

window.PORTFOLIO_DATA = {
  identity: {
    handle: "your_handle",
    title: "Your Title / Your Specialty",
    location: "Your City — Remote",
    summary:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.",
    stats: [
      { label: "PROJECTS", value: "00" },
      { label: "DEPLOYED MODELS", value: "00" },
      { label: "COMPETITIONS", value: "00" },
      { label: "YEARS", value: "00" },
    ],
  },

  projects: [
    {
      id: "p1",
      name: "PROJECT.alpha",
      domain: "AI",
      year: "2025",
      tag: "Production",
      tagline: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
      description:
        "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      stack: ["lorum ipsum"],
      features: [
        "Lorem ipsum dolor sit amet consectetur",
        "Sed do eiusmod tempor incididunt ut labore",
        "Ut enim ad minim veniam quis nostrud",
        "Excepteur sint occaecat cupidatat non proident",
      ],
      fields: ["ml", "web"],
      x: 0.18, y: 0.32,
    },
    {
      id: "p2",
      name: "PROJECT.beta",
      domain: "AI",
      year: "2025",
      tag: "Research",
      tagline: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
      description:
        "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.",
      stack: ["lorum ipsum"],
      features: [
        "Neque porro quisquam est qui dolorem",
        "Ipsum quia dolor sit amet consectetur",
        "Adipisci velit sed quia non numquam",
        "Eius modi tempora incidunt ut labore",
      ],
      fields: ["agentic", "ml"],
      x: 0.32, y: 0.18,
    },
    {
      id: "p3",
      name: "PROJECT.gamma",
      domain: "Web",
      year: "2024",
      tag: "Open Source",
      tagline: "At vero eos et accusamus et iusto odio dignissimos ducimus.",
      description:
        "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae.",
      stack: ["lorum ipsum"],
      features: [
        "Itaque earum rerum hic tenetur",
        "A sapiente delectus ut aut reiciendis",
        "Voluptatibus maiores alias consequatur",
        "Aut perferendis doloribus asperiores",
      ],
      fields: ["web"],
      x: 0.5, y: 0.36,
    },
    {
      id: "p4",
      name: "PROJECT.delta",
      domain: "Cyber",
      year: "2024",
      tag: "Production",
      tagline: "Quis autem vel eum iure reprehenderit qui in ea voluptate velit.",
      description:
        "Nam libero tempore cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus.",
      stack: ["lorum ipsum"],
      features: [
        "Omnis voluptas assumenda est omnis dolor",
        "Repellendus temporibus autem quibusdam",
        "Et aut officiis debitis aut rerum",
        "Necessitatibus saepe eveniet ut et",
      ],
      fields: ["cyber", "ml", "devops"],
      x: 0.7, y: 0.22,
    },
    {
      id: "p5",
      name: "PROJECT.epsilon",
      domain: "Web",
      year: "2024",
      tag: "Personal",
      tagline: "Nemo enim ipsam voluptatem quia voluptas sit aspernatur.",
      description:
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.",
      stack: ["lorum ipsum"],
      features: [
        "Eaque ipsa quae ab illo inventore",
        "Veritatis et quasi architecto beatae",
        "Vitae dicta sunt explicabo",
        "Nemo enim ipsam voluptatem quia",
      ],
      fields: ["web"],
      x: 0.84, y: 0.42,
    },
    {
      id: "p6",
      name: "PROJECT.zeta",
      domain: "Cyber",
      year: "2023",
      tag: "Research",
      tagline: "Ut enim ad minima veniam quis nostrum exercitationem ullam.",
      description:
        "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.",
      stack: ["lorum ipsum"],
      features: [
        "Vel illum qui dolorem eum fugiat",
        "Quo voluptas nulla pariatur",
        "At vero eos et accusamus",
        "Et iusto odio dignissimos ducimus",
      ],
      fields: ["cyber", "agentic"],
      x: 0.62, y: 0.62,
    },
    {
      id: "p7",
      name: "PROJECT.eta",
      domain: "Web",
      year: "2023",
      tag: "Open Source",
      tagline: "Excepteur sint occaecat cupidatat non proident sunt in culpa.",
      description:
        "Sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error sit.",
      stack: ["lorum ipsum"],
      features: [
        "Duis aute irure dolor in reprehenderit",
        "In voluptate velit esse cillum",
        "Dolore eu fugiat nulla pariatur",
        "Excepteur sint occaecat cupidatat",
      ],
      fields: ["web"],
      x: 0.38, y: 0.74,
    },
    {
      id: "p8",
      name: "PROJECT.theta",
      domain: "AI",
      year: "2023",
      tag: "Research",
      tagline: "Lorem ipsum dolor sit amet consectetur adipiscing elit sed do.",
      description:
        "Eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.",
      stack: ["lorum ipsum"],
      features: [
        "Ex ea commodo consequat duis aute",
        "Irure dolor in reprehenderit",
        "In voluptate velit esse cillum dolore",
      ],
      fields: ["agentic", "ml"],
      x: 0.16, y: 0.62,
    },
    {
      id: "p9",
      name: "PROJECT.iota",
      domain: "DevOps",
      year: "2024",
      tag: "Production",
      tagline: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
      description:
        "Accusantium doloremque laudantium totam rem aperiam eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
      stack: ["lorum ipsum"],
      features: [
        "Nemo enim ipsam voluptatem quia voluptas",
        "Sit aspernatur aut odit aut fugit",
        "Sed quia consequuntur magni dolores",
        "Eos qui ratione voluptatem sequi",
      ],
      fields: ["devops", "cloud"],
      x: 0.76, y: 0.78,
    },
    {
      id: "p10",
      name: "PROJECT.kappa",
      domain: "Cloud",
      year: "2025",
      tag: "Open Source",
      tagline: "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet.",
      description:
        "Consectetur adipisci velit sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
      stack: ["lorum ipsum"],
      features: [
        "Ut enim ad minima veniam quis nostrum",
        "Exercitationem ullam corporis suscipit",
        "Laboriosam nisi ut aliquid ex ea",
        "Commodi consequatur quis autem vel eum",
      ],
      fields: ["cloud", "devops"],
      x: 0.5, y: 0.86,
    },
    {
      id: "p11",
      name: "PROJECT.lambda",
      domain: "DevOps",
      year: "2024",
      tag: "Personal",
      tagline: "Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea.",
      description:
        "Commodo consequat duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      stack: ["lorum ipsum"],
      features: [
        "Excepteur sint occaecat cupidatat",
        "Non proident sunt in culpa qui officia",
        "Deserunt mollit anim id est laborum",
        "Sed ut perspiciatis unde omnis iste",
      ],
      fields: ["devops", "cyber"],
      x: 0.06, y: 0.86,
    },
  ],

  // edges between projects, by id pair, with relation
  projectEdges: [
    ["p1", "p2", "lorem-ipsum"],
    ["p1", "p3", "dolor-sit"],
    ["p2", "p3", "amet-consec"],
    ["p2", "p8", "adipiscing"],
    ["p3", "p5", "elit-sed"],
    ["p3", "p4", "do-eiusmod"],
    ["p4", "p6", "tempor"],
    ["p1", "p7", "incididunt"],
    ["p7", "p5", "ut-labore"],
    ["p2", "p7", "et-dolore"],
    ["p1", "p8", "magna"],
    ["p6", "p4", "aliqua"],
  ],

  achievements: [
    { id: "a1", name: "Lorem Ipsum Conference", year: "2024", type: "talk", note: "Lorem ipsum dolor sit amet", cluster: "research" },
    { id: "a2", name: "Dolor Sit Workshop", year: "2024", type: "paper", note: "Consectetur adipiscing elit", cluster: "research" },
    { id: "a3", name: "Amet Competition", year: "2023", type: "rank", note: "Sed do eiusmod tempor", cluster: "competitions" },
    { id: "a4", name: "Consectetur Hackathon", year: "2024", type: "win", note: "Ut enim ad minim veniam", cluster: "competitions" },
    { id: "a5", name: "Adipiscing Regionals", year: "2022", type: "win", note: "Quis nostrud exercitation", cluster: "competitions" },
    { id: "a6", name: "Elit Open Source Award", year: "2025", type: "rank", note: "Ullamco laboris nisi", cluster: "open-source" },
    { id: "a7", name: "PROJECT.beta — 0.0k★", year: "2025", type: "release", note: "Ut aliquip ex ea commodo", cluster: "open-source" },
    { id: "a8", name: "PROJECT.gamma — 0.0k★", year: "2024", type: "release", note: "Consequat duis aute irure", cluster: "open-source" },
    { id: "a9", name: "Lorem Press Feature", year: "2025", type: "press", note: "Dolor in reprehenderit", cluster: "press" },
    { id: "a10", name: "Ipsum Magazine", year: "2024", type: "press", note: "In voluptate velit esse", cluster: "press" },
  ],
};
