/* Portfolio data — original content for "Aloysius Lim" persona */

/* Field hubs — large nodes that projects orbit around */
window.PROJECT_FIELDS = [
  { id: "ml",      label: "ML",       color: "#00f5ff", angle: -Math.PI * 0.5 },
  { id: "web",     label: "Web",      color: "#9d00ff", angle: -Math.PI * 0.166 },
  { id: "agentic", label: "Agentic",  color: "#5eead4", angle:  Math.PI * 0.166 },
  { id: "cyber",   label: "Cyber",    color: "#ff2bd6", angle:  Math.PI * 0.5 },
  { id: "devops",  label: "DevOps",   color: "#ffc857", angle:  Math.PI * 0.833 },
  { id: "cloud",   label: "Cloud",    color: "#7dd3fc", angle: -Math.PI * 0.833 },
];

window.PORTFOLIO_DATA = {
  identity: {
    handle: "aloysius_lim",
    title: "AI Systems Engineer / Interface Architect",
    location: "Singapore — Remote",
    summary:
      "I build interfaces between humans and intelligent systems — from neural search engines to multi-agent orchestration tools. Currently exploring graph-native UX and embodied AI.",
    stats: [
      { label: "PROJECTS", value: "24" },
      { label: "DEPLOYED MODELS", value: "11" },
      { label: "COMPETITIONS", value: "07" },
      { label: "YEARS", value: "05" },
    ],
  },

  projects: [
    {
      id: "p1",
      name: "SYNAPSE.search",
      domain: "AI",
      year: "2025",
      tag: "Production",
      tagline: "Vector-native search across 40M docs in <80ms.",
      description:
        "A graph-aware semantic search engine that fuses dense retrieval with knowledge-graph reasoning. Used internally to navigate engineering docs.",
      stack: ["Rust", "PyTorch", "FAISS", "Neo4j", "Next.js"],
      features: [
        "Hybrid retrieval (BM25 + dense + graph hop)",
        "Streaming answer composer",
        "Sub-80ms p95 over 40M chunks",
        "Self-hosted reranker (200M params)",
      ],
      fields: ["ml", "web"],
      x: 0.18, y: 0.32,
    },
    {
      id: "p2",
      name: "MIRROR.agent",
      domain: "AI",
      year: "2025",
      tag: "Research",
      tagline: "A multi-agent system that debates itself into clarity.",
      description:
        "Self-reflective agent loop: planner, critic, executor, and a memory consolidator that distills runs into a knowledge graph.",
      stack: ["Python", "LangGraph", "Postgres", "Redis"],
      features: [
        "5-role debate protocol",
        "Long-term episodic memory",
        "Tool-use grounding via JSON schema",
        "Open-source, 4.1k stars",
      ],
      fields: ["agentic", "ml"],
      x: 0.32, y: 0.18,
    },
    {
      id: "p3",
      name: "GRID.viz",
      domain: "Web",
      year: "2024",
      tag: "Open Source",
      tagline: "WebGL force-graph for 1M+ nodes at 60fps.",
      description:
        "A GPU-accelerated graph rendering library. Powers the visualization layer of three of the projects on this page.",
      stack: ["TypeScript", "WebGL2", "Rust→WASM"],
      features: [
        "Compute shader physics",
        "Quadtree culling",
        "1M+ nodes @ 60fps",
        "Hot-swappable layouts",
      ],
      fields: ["web"],
      x: 0.5, y: 0.36,
    },
    {
      id: "p4",
      name: "COVENANT.ids",
      domain: "Cyber",
      year: "2024",
      tag: "Production",
      tagline: "Anomaly detection for service mesh telemetry.",
      description:
        "Streaming anomaly detector built on a graph autoencoder. Runs inline on Envoy sidecars; flags lateral movement in <300ms.",
      stack: ["Go", "PyTorch", "Kafka", "ClickHouse"],
      features: [
        "Graph autoencoder (24M params)",
        "<300ms detection",
        "Zero-copy sidecar integration",
        "Adversarial robustness eval",
      ],
      fields: ["cyber", "ml", "devops"],
      x: 0.7, y: 0.22,
    },
    {
      id: "p5",
      name: "ATLAS.os",
      domain: "Web",
      year: "2024",
      tag: "Personal",
      tagline: "A tiling, command-driven web OS for my browser.",
      description:
        "Window manager + command palette + plugin system, all in the browser. I live in this thing — calendar, mail, notes, terminal.",
      stack: ["React", "Vite", "IndexedDB", "Tauri"],
      features: [
        "Tiling window manager",
        "Plugin sandbox (iframe + postMessage)",
        "Cmd-K everything",
        "Offline-first sync",
      ],
      fields: ["web"],
      x: 0.84, y: 0.42,
    },
    {
      id: "p6",
      name: "REDLINE.fuzz",
      domain: "Cyber",
      year: "2023",
      tag: "Research",
      tagline: "LLM-guided fuzzer that found 14 CVEs.",
      description:
        "Coverage-guided fuzzer where an LLM proposes payloads from crash context. Reported 14 CVEs in OSS parsers.",
      stack: ["Rust", "AFL++", "OpenAI API"],
      features: [
        "Crash-context prompt",
        "Coverage delta reward",
        "14 confirmed CVEs",
        "Talk @ Black Hat Asia",
      ],
      fields: ["cyber", "agentic"],
      x: 0.62, y: 0.62,
    },
    {
      id: "p7",
      name: "ECHO.ui",
      domain: "Web",
      year: "2023",
      tag: "Open Source",
      tagline: "Voice-first design system for AI surfaces.",
      description:
        "A component library of conversational primitives: streaming bubbles, citation chips, tool-call cards, audio waveforms.",
      stack: ["React", "Web Audio", "Framer Motion"],
      features: [
        "32 components",
        "Streaming-first APIs",
        "WCAG AA",
        "1.2k stars",
      ],
      fields: ["web"],
      x: 0.38, y: 0.74,
    },
    {
      id: "p8",
      name: "ORACLE.bench",
      domain: "AI",
      year: "2023",
      tag: "Research",
      tagline: "Benchmark for agent failure modes.",
      description:
        "A taxonomy + 4,200-task benchmark targeting the long tail of agent failures: tool misuse, loop traps, hallucinated state.",
      stack: ["Python", "DSPy", "DuckDB"],
      features: [
        "4.2k tasks across 12 domains",
        "Failure-mode taxonomy",
        "Cited by 6 papers",
      ],
      fields: ["agentic", "ml"],
      x: 0.16, y: 0.62,
    },
    {
      id: "p9",
      name: "HELIX.deploy",
      domain: "DevOps",
      year: "2024",
      tag: "Production",
      tagline: "GitOps pipeline orchestrator with policy-as-code.",
      description:
        "Multi-cluster Kubernetes deploy controller. Argo-style sync with OPA policy gates and Prometheus-driven canaries.",
      stack: ["Go", "Kubernetes", "ArgoCD", "Prometheus", "OPA"],
      features: [
        "Drift detection across 6 clusters",
        "Policy-gated promotion",
        "Auto-rollback on SLO burn",
        "Grafana dashboards",
      ],
      fields: ["devops", "cloud"],
      x: 0.76, y: 0.78,
    },
    {
      id: "p10",
      name: "TERRA.mesh",
      domain: "Cloud",
      year: "2025",
      tag: "Open Source",
      tagline: "Multi-cloud Terraform module registry + drift watcher.",
      description:
        "Federated Terraform module registry across AWS and GCP with continuous drift reconciliation and cost telemetry.",
      stack: ["Terraform", "AWS", "GCP", "Pulumi", "Go"],
      features: [
        "AWS + GCP unified IaC",
        "Hourly drift scans",
        "Cost-aware module advisor",
        "1.4k stars",
      ],
      fields: ["cloud", "devops"],
      x: 0.5, y: 0.86,
    },
    {
      id: "p11",
      name: "PULSE.observe",
      domain: "DevOps",
      year: "2024",
      tag: "Personal",
      tagline: "Self-hosted observability stack on a Raspberry Pi cluster.",
      description:
        "Prometheus + Grafana + Loki on bare-metal k3s. Used to monitor my homelab and side-project services.",
      stack: ["Prometheus", "Grafana", "Loki", "k3s", "Linux"],
      features: [
        "5-node k3s cluster",
        "30-day metric retention",
        "Custom Wireshark exporter",
        "Webhook → Telegram alerts",
      ],
      fields: ["devops", "cyber"],
      x: 0.06, y: 0.86,
    },
  ],

  // edges between projects, by id pair, with relation
  projectEdges: [
    ["p1", "p2", "graph-memory"],
    ["p1", "p3", "viz layer"],
    ["p2", "p3", "viz layer"],
    ["p2", "p8", "agent eval"],
    ["p3", "p5", "ui shell"],
    ["p3", "p4", "viz layer"],
    ["p4", "p6", "security"],
    ["p1", "p7", "shared ux"],
    ["p7", "p5", "shared ux"],
    ["p2", "p7", "shared ux"],
    ["p1", "p8", "retrieval"],
    ["p6", "p4", "shared infra"],
  ],

  achievements: [
    { id: "a1", name: "Black Hat Asia", year: "2024", type: "talk", note: "Speaker — LLM-guided fuzzing", cluster: "research" },
    { id: "a2", name: "NeurIPS Workshop", year: "2024", type: "paper", note: "Co-author, MIRROR agents", cluster: "research" },
    { id: "a3", name: "Kaggle Grandmaster", year: "2023", type: "rank", note: "Top 0.1% — 4 golds", cluster: "competitions" },
    { id: "a4", name: "AI Singapore Hack", year: "2024", type: "win", note: "1st place / 412 teams", cluster: "competitions" },
    { id: "a5", name: "ICPC Regionals", year: "2022", type: "win", note: "Bronze — Asia Pacific", cluster: "competitions" },
    { id: "a6", name: "GitHub Stars", year: "2025", type: "rank", note: "Featured developer", cluster: "open-source" },
    { id: "a7", name: "MIRROR — 4.1k★", year: "2025", type: "release", note: "Top of HN, 1 day", cluster: "open-source" },
    { id: "a8", name: "GRID.viz — 2.8k★", year: "2024", type: "release", note: "Showcase: Three.js Journey", cluster: "open-source" },
    { id: "a9", name: "Forbes 30u30 SEA", year: "2025", type: "press", note: "Tech / Enterprise", cluster: "press" },
    { id: "a10", name: "CACM feature", year: "2024", type: "press", note: "Cover essay on agents", cluster: "press" },
  ],
};
