/* Leadership roles and event data */
window.LEADERSHIP_DATA = {
  roles: [
    {
      id: "r1",
      title: "Manpower Department Member",
      org: "Sunway Diploma Studies Student Council",
      term: "September 2024 — September 2025",
      summary: "Coordinated manpower deployment and provided operational support during student council events, ensuring smooth event execution and adherence to planned itineraries.",
      stat: "00",
      statLabel: "member",
    },
    {
      id: "r2",
      title: "Event Department Sub-Director",
      org: "Sunway Analytics Society",
      term: "May 2025 - Present",
      summary: "Initiates the planning and execution of society events, from event brainstorming to pre-event planning and post-event mortem. Involved in event coordination, departmental liaison, and handling communication with external parties and speakers.",
      stat: "01",
      statLabel: "Board of Director (BoD)",
    },
    {
      id: "r3",
      title: "Head of Education Department",
      org: "Sunway Tech Club",
      term: "May 2026 - Present",
      summary: "Leading the Education Department and overseeing the planning and execution of all events in Sunway Tech Club.",
      stat: "02",
      statLabel: "Executive Committee",
    },
  ],
  events: [
    {
      id: "e1", name: "Valentine Event 2025", role: "Manpower Member", club: "Sunway Diploma Studies Student Council",
      collaborator: "Sunway Diploma Studies",
      participants: "100+", date: "March 2025", year: "2025",
      tagline: "A successful Valentine's Event with 100+ participants.",
      overview: "Helped out with the event, being on the manpower department and making sure the event ran smoothly.",
      outcomes: ["Leader of one of the event booth.", "Facilitated a non-alcoholic beer pong game for my event booth."],
      images: [
        "/assets/events/e1-valentine-1.webp",
      ],
      instagram: "https://www.instagram.com/p/DGSm8uuzGd6/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      x: 0.18, y: 0.32,
    },
    {
      id: "e2", name: "Tech Career Network: How Companies Hire Fresh Talent", role: "Event Lead", club: "Sunway Analytics Society",
      collaborator: "TalentsLab, Experion, BASF, U Mobile", speaker: "Crystine Yoong, Michelle Wong, Wong Yew Li",
      participants: "50", date: "July 2025", year: "2025",
      tagline: "Connecting emerging tech talent with the companies shaping their next move.",
      overview: "A panel discussion event featuring industry leaders from various companies, discussing topics related to hiring fresh talent in the tech industry. The event was attended by 50 participants, who engaged in Q&A sessions with the speakers.",
      outcomes: ["Successfully launched the panel discussion event with smooth flow", "Facilitated an open networking session, which allows participants to engage directly with industry leaders."],
      images: [
        "/assets/events/e2-tech-career-network-1.webp",
        "/assets/events/e2-tech-career-network-2.webp",
        "/assets/events/e2-tech-career-network-3.webp",
      ],
      linkedin: "https://www.linkedin.com/posts/sunway-analytics-society_sunwayanalyticssociety-sunwayuniversity-sunwaycollege-activity-7359810689760202752-KF0p?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFaeq70BBT09D-OoL-2gVND-yiBm4zlaJ8s",
      instagram: "https://www.instagram.com/p/DNHytHsTIro/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      x: 0.4, y: 0.18,
    },
    {
      id: "e3", name: "Generative AI Fundamentals", role: "Event Lead", club: "Sunway Analytics Society",
      collaborator: "Growth.Pro", speaker: "Ng Keng Fai",
      participants: "20", date: "September 2025", year: "2025",
      tagline: "",
      overview: "An online workshop event featuring experienced speaker from Growth.Pro, discussing topics related to generative AI fundamentals. The event was attended by 30 participants.",
      outcomes: ["Successfully hosted an online workshop joined with 20 participants", "Taught participants with the fundamentals of generative AI like Prompt Engineering, LLM use cases, Multimodality & Productivity"],
      images: [
        "/assets/events/e3-generative-ai-fundamentals-1.webp",
        "/assets/events/e3-generative-ai-fundamentals-2.webp",
        "/assets/events/e3-generative-ai-fundamentals-3.webp",
      ],
      linkedin: "https://www.linkedin.com/posts/sunway-analytics-society_sunwayanalyticssociety-sunwayuniversity-sunwaycollege-activity-7377567670034092032-njsh?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFaeq70BBT09D-OoL-2gVND-yiBm4zlaJ8s",
      instagram: "https://www.instagram.com/p/DPF9nWPk2ak/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      x: 0.62, y: 0.32,
    },
    {
      id: "e4", name: "Smart Marketing with Generative AI", role: "Event Lead", club: "Sunway Analytics Society",
      collaborator: "Growth.Pro", speaker: "Ng Keng Fai",
      participants: "10", date: "September 2025", year: "2025",
      tagline: "",
      overview: "An online workshop event featuring experienced speaker from Growth.Pro, discussing topics related to smart marketing with generative AI. The event was attended by 10 participants.",
      outcomes: ["Successfully conducted 4 modules during the 3 hour session", "Taught participants on how to use AI effectively in marketing campaigns, content creation and analytics."],
      images: [
        "/assets/events/e4-smart-marketing-generative-ai-1.webp",
        "/assets/events/e4-smart-marketing-generative-ai-2.webp",
        "/assets/events/e4-smart-marketing-generative-ai-3.webp",
      ],
      linkedin: "https://www.linkedin.com/posts/sunway-analytics-society_sunwayanalyticssociety-sunwayuniversity-sunwaycollege-activity-7380104398292713473-ITj7?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFaeq70BBT09D-OoL-2gVND-yiBm4zlaJ8s",
      instagram: "https://www.instagram.com/p/DPX_MTCE3ed/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      x: 0.82, y: 0.5,
    },
    {
      id: "e5", name: "WorldQuant Alphathon Workshop 2025", role: "Event Lead", club: "Sunway Analytics Society",
      collaborator: "WorldQuant Singapore", speaker: "Terence",
      participants: "50", date: "November 2025", year: "2025",
      tagline: "A practical introduction to quantitative finance and WorldQuant's BRAIN platform.",
      overview: "A Workshop hosted in collaboration with WorldQuant to serve as a kick start event for the upcoming WorldQuant Alphathon Competition 2025.",
      outcomes: ["Introducing participants to the world of quantitative finance, as well as WorldQuant's BRAIN platform.", "Familiarizing participants with the rules and format of the WorldQuant Alphathon competition."],
      images: [
        "/assets/events/e5-worldquant-alphathon-1.webp",
        "/assets/events/e5-worldquant-alphathon-2.webp",
        "/assets/events/e5-worldquant-alphathon-3.webp",
      ],
      linkedin: "https://www.linkedin.com/posts/sunway-analytics-society_sunwayanalyticssociety-sunwayuniversity-sunwaycollege-activity-7400065931286093824-pwaZ?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFaeq70BBT09D-OoL-2gVND-yiBm4zlaJ8s",
      instagram: "https://www.instagram.com/p/DRoZbFakzbZ/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      x: 0.62, y: 0.32,
    },
    {
      id: "e6", name: "Careers in Data Analytics", role: "Event Lead", club: "Sunway Analytics Society",
      speaker: "Yong Wai Shin (Data Team Lead, Decathlon Malaysia)",
      participants: "13", date: "June 2026", year: "2026",
      tagline: "A practical look at the skills, responsibilities, and pathways behind a career in data analytics.",
      overview: "An industry career talk for Sunway College and Sunway University students interested in data analytics. The session explored a data analyst's daily responsibilities, essential skills, entry-level expectations, and available career and internship pathways.",
      outcomes: [
        "Gave participants a practical understanding of a data analyst's day-to-day responsibilities and entry requirements",
        "Raised awareness of data analytics career opportunities and their role in today's industrial landscape",
        "Provided an open Q&A on career paths, internships, and entering the field",
      ],
      images: [
        "/assets/events/e6-careers-data-analytics-1.webp",
        "/assets/events/e6-careers-data-analytics-2.webp",
        "/assets/events/e6-careers-data-analytics-3.webp",
      ],
      linkedin: "https://www.linkedin.com/posts/sunway-analytics-society_sunwayanalyticssociety-sunwayuniversity-sunwaycollege-activity-7477707808545775618-KlO4?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFaeq70BBT09D-OoL-2gVND-yiBm4zlaJ8s",
      instagram: "https://www.instagram.com/p/DaNf8-jgY7l/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==&igsi=MzRlODBiNWFlZA==",
      x: 0.18, y: 0.32,
    },
    {
      id: "e7", name: "Careers in AI and Data Analytics", role: "Event Lead", club: "Sunway Analytics Society",
      speaker: "Teng Qian Wen (Project Manager, YWVision)",
      participants: "10", date: "June 2026", year: "2026",
      tagline: "Exploring two fast-growing career paths at the intersection of data and AI.",
      overview: "A career guidance talk for Sunway College and Sunway University students interested in data analytics and artificial intelligence. The session compared the roles of data analysts and AI engineers, covering their responsibilities, required skills, entry pathways, and industry trends.",
      outcomes: [
        "Highlighted job opportunities, responsibilities, and industry trends for data analysts and AI engineers",
        "Explained the day-to-day work and entry requirements for both career paths",
        "Provided a Q&A for students to explore each profession in greater depth",
      ],
      images: [
        "/assets/events/e7-careers-ai-data-analytics-1.webp",
        "/assets/events/e7-careers-ai-data-analytics-2.webp",
        "/assets/events/e7-careers-ai-data-analytics-3.webp",
      ],
      linkedin: "https://www.linkedin.com/posts/sunway-analytics-society_sunwayanalyticssociety-sunwayuniversity-sunwaycollege-activity-7477934026192764928-KqqH?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFaeq70BBT09D-OoL-2gVND-yiBm4zlaJ8s",
      instagram: "https://www.instagram.com/p/DaPG8YfDD0R/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==&igsi=MzRlODBiNWFlZA==",
      x: 0.4, y: 0.18,
    },
    {
      id: "e8", name: "Backend 101: Build Your Own API", role: "Head of Events", club: "Sunway Tech Club",
      speaker: "Sean Hoe Kai Zher",
      participants: "30", date: "July 2026", year: "2026",
      tagline: "Build and test your first REST API with Express.js and Postman.",
      overview: "A hands on workshop featuring on building and testing your very own API using ExpressJS and Postman, all in JavaScript. This workshop serves as the first step into the world of backend development",
      outcomes: ["Successfully conducted backend REST API development in Express JS", "Performed API testing using postman server."],
      images: [
        "/assets/events/e8-backend-101-1.webp",
        "/assets/events/e8-backend-101-2.webp",
      ],
      instagram: "https://www.instagram.com/p/DaM4E1NzVfp/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==&igsi=MzRlODBiNWFlZA==",
      x: 0.82, y: 0.5,
    },
    {
      id: "e9", name: "Tech & Engineering Career Fair 2026", role: "Event Co-Lead", club: "Sunway Analytics Society",
      collaborator: "23 companies",
      participants: "500+", date: "July 2026", year: "2026",
      tagline: "Bringing 500+ students face-to-face with 23 technology and engineering employers.",
      overview: "A faculty wide event to provide a special opportunity for students studying in the fields of technology and engineering, as well as other fields of study to connect with future employers and seek for potential internship or job opportunities",
      outcomes: ["Successfully liaising with 23 SMB & MNC companies to attend this career fair for Faculty of Engineering & Technology students", "Attended by over 500+ participants from Sunway College and Sunway University", "Coordinated interview session opportunities with 5 different companies and joined by 10-20 students."],
      images: [
        "/assets/events/e9-career-fair-1.webp",
        "/assets/events/e9-career-fair-2.webp",
        "/assets/events/e9-career-fair-3.webp",
      ],
      instagram: "https://www.instagram.com/p/Dbus-9LAQjz",
      linkedin: "https://www.linkedin.com/posts/sunway-analytics-society_sunwayanalyticssociety-sunwayuniversity-sunwaycollege-ugcPost-7490792487897174016-VEaW/?utm_source=share&utm_medium=member_desktop&rcm=ACoAAFaeq70BBT09D-OoL-2gVND-yiBm4zlaJ8s",
      x: 0.32, y: 0.62,
    },
    {
      id: "e10", name: "Build a LangChain RAG Agent with Gemini", role: "Event Lead", club: "Sunway Tech Club",
      speaker: "Leong Lai Fong (Senior AI Engineer, BASF)",
      participants: "20", date: "July 2026", year: "2026",
      tagline: "Build a retrieval-augmented Gemini agent with LangChain, guided by an industry AI engineer.",
      overview: "A hands-on workshop on Retrieval-Augmented Generation (RAG) with LangChain and Gemini. Led by an industry AI engineer, the session combined core concepts with a live implementation to help students understand how modern AI agents retrieve and use external knowledge.",
      outcomes: [
        "Introduced the foundations and practical use cases of Retrieval-Augmented Generation",
        "Gave participants hands-on experience building with LangChain and Gemini",
        "Connected academic AI concepts with current industry development practices through an expert-led demonstration",
      ],
      images: [
        "/assets/events/e10-langchain-rag-gemini-1.webp",
        "/assets/events/e10-langchain-rag-gemini-2.webp",
        "/assets/events/e10-langchain-rag-gemini-3.webp",
      ],
      instagram: "https://www.instagram.com/p/DbPW_7BTwLB/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==&igsi=MzRlODBiNWFlZA==",
      x: 0.62, y: 0.32,
    },
  ],
  edges: [
    ["e1", "e2"], ["e5", "e1"], ["e3", "e2"], ["e4", "e3"],
    ["e4", "e5"], ["e2", "e6"], ["e2", "e7"], ["e6", "e7"],
    ["e1", "e9"], ["e8", "e1"], ["e9", "e2"], ["e8", "e5"],
    ["e8", "e10"], ["e3", "e10"],
  ],
};
