/* Leadership data — placeholder content (lorem ipsum) */
window.LEADERSHIP_DATA = {
  roles: [
    {
      id: "r1",
      title: "Lorem Ipsum",
      org: "Dolor Sit Amet Organization",
      term: "2024 — present",
      summary: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.",
      stat: "00",
      statLabel: "member",
    },
    {
      id: "r2",
      title: "Consectetur Lead",
      org: "Adipiscing Guild",
      term: "2023 — 2024",
      summary: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.",
      stat: "00",
      statLabel: "member",
    },
    {
      id: "r3",
      title: "Sed Do Curator",
      org: "Eiusmod Tempor Community",
      term: "2023 — present",
      summary: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      stat: "00",
      statLabel: "member",
    },
    {
      id: "r4",
      title: "Founding Member",
      org: "Magna Aliqua Collective",
      term: "2025 — present",
      summary: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est.",
      stat: "00",
      statLabel: "member",
    },
  ],
  events: [
    {
      id: "e1", name: "Lorem Summit", role: "Lead Organizer", club: "Dolor Chapter",
      collaborator: "Sit Amet Corp", speaker: "Dr. Lorem Ipsum",
      participants: "000", date: "March 2025", year: "2025",
      tagline: "Lorem ipsum dolor sit amet consectetur adipiscing elit.",
      overview: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
      outcomes: ["Lorem ipsum dolor sit amet", "Consectetur adipiscing elit", "Sed do eiusmod tempor", "Incididunt ut labore et dolore"],
      linkedin: "#",
      x: 0.18, y: 0.32,
    },
    {
      id: "e2", name: "Ipsum Hackathon", role: "Tech Lead", club: "Amet Guild",
      collaborator: "Consectetur Inc", speaker: "Lin Dolor",
      participants: "000", date: "August 2024", year: "2024",
      tagline: "Ut enim ad minim veniam quis nostrud exercitation ullamco.",
      overview: "Laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.",
      outcomes: ["Quis nostrud exercitation", "Ullamco laboris nisi", "Ut aliquip ex ea commodo"],
      linkedin: "#",
      x: 0.4, y: 0.18,
    },
    {
      id: "e3", name: "Reading Group: Lorem Ipsum", role: "Curator", club: "Dolor-SEA",
      collaborator: "Sit amet alumni network", speaker: "Various",
      participants: "00", date: "Recurring · 2023→", year: "2023→",
      tagline: "Duis aute irure dolor in reprehenderit in voluptate velit.",
      overview: "Esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
      outcomes: ["Excepteur sint occaecat", "Cupidatat non proident", "Sunt in culpa qui officia"],
      linkedin: "#",
      x: 0.62, y: 0.32,
    },
    {
      id: "e4", name: "Amet Demo Night", role: "MC + Curator", club: "NIC",
      collaborator: "Adipiscing SEA", speaker: "Panel of 5 speakers",
      participants: "000", date: "October 2025", year: "2025",
      tagline: "Nam libero tempore cum soluta nobis est eligendi optio.",
      overview: "Cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis.",
      outcomes: ["Lorem ipsum dolor sit", "Amet consectetur adipiscing", "Elit sed do eiusmod"],
      linkedin: "#",
      x: 0.82, y: 0.5,
    },
    {
      id: "e5", name: "Consectetur Mentorship", role: "Mentor + Track Lead", club: "Dolor Chapter",
      collaborator: "Adipiscing Singapore", speaker: "Dr. Priya Lorem",
      participants: "00", date: "2024 — 2025", year: "2024",
      tagline: "At vero eos et accusamus et iusto odio dignissimos ducimus.",
      overview: "Qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
      outcomes: ["Similique sunt in culpa", "Qui officia deserunt mollitia", "Animi id est laborum et dolorum"],
      linkedin: "#",
      x: 0.32, y: 0.62,
    },
    {
      id: "e6", name: "Open Source Drive", role: "Sprint Captain", club: "Dolor-SEA",
      collaborator: "Sit Amet Foundation", speaker: "Self-led",
      participants: "000", date: "May 2024", year: "2024",
      tagline: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem.",
      overview: "Accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.",
      outcomes: ["Nemo enim ipsam voluptatem", "Quia voluptas sit aspernatur", "Aut odit aut fugit sed quia"],
      linkedin: "#",
      x: 0.55, y: 0.7,
    },
  ],
  edges: [
    ["e1", "e2"], ["e2", "e6"], ["e3", "e1"], ["e1", "e5"], ["e4", "e1"], ["e3", "e6"], ["e5", "e2"], ["e4", "e3"],
  ],
};
