/* Leadership data — roles + led events */
window.LEADERSHIP_DATA = {
  roles: [
    {
      id: "r1",
      title: "President",
      org: "AI Singapore Student Chapter",
      term: "2024 — present",
      summary: "Lead 142-member chapter; secured 5 industry partners; ran 18 events.",
      stat: "142",
      statLabel: "members",
    },
    {
      id: "r2",
      title: "Tech Lead",
      org: "GovTech Hackers Guild",
      term: "2023 — 2024",
      summary: "Mentored 24 juniors. Built infra and review pipeline for 6 hackathons.",
      stat: "24",
      statLabel: "mentees",
    },
    {
      id: "r3",
      title: "Community Curator",
      org: "Open Source SEA",
      term: "2023 — present",
      summary: "Curate monthly graph-theory & ML reading group. 480 subscribers.",
      stat: "480",
      statLabel: "subs",
    },
    {
      id: "r4",
      title: "Founding Member",
      org: "Neural Interface Collective",
      term: "2025 — present",
      summary: "Co-founded research collective on graph-native interfaces.",
      stat: "07",
      statLabel: "founders",
    },
  ],
  events: [
    {
      id: "e1", name: "GraphAI Summit", role: "Lead Organizer", club: "AISG Chapter",
      collaborator: "AI Singapore", speaker: "Dr. Mei Zhao",
      participants: "320", date: "March 2025", year: "2025",
      tagline: "Day-long conference on graph-native machine learning.",
      overview: "A 320-attendee summit bringing together graph-ML researchers from NUS, NTU, A*STAR and three industry sponsors. I led a 12-person organizing team across logistics, sponsorship, content curation and post-event analytics. Talks were live-streamed and the recording archive crossed 18k views.",
      outcomes: ["320 in-person attendees", "S$24K sponsorship secured", "12 talks across 3 tracks", "18k+ post-event views"],
      linkedin: "#",
      x: 0.18, y: 0.32,
    },
    {
      id: "e2", name: "Hack the Grid 2024", role: "Tech Lead", club: "Hackers Guild",
      collaborator: "GovTech", speaker: "Lin Wei",
      participants: "412", date: "August 2024", year: "2024",
      tagline: "48-hour civic-tech hackathon on national grid resilience.",
      overview: "Co-led a 48-hour hackathon with 412 participants across 86 teams. Designed the judging rubric, ran the infra (gateway + submission portal), and mentored 6 finalist teams to deployable prototypes.",
      outcomes: ["412 participants / 86 teams", "Zero infra downtime", "6 prototypes shipped to GovTech sandbox"],
      linkedin: "#",
      x: 0.4, y: 0.18,
    },
    {
      id: "e3", name: "Reading Group: Geometric Deep Learning", role: "Curator", club: "OSS-SEA",
      collaborator: "DeepMind alumni network", speaker: "Various",
      participants: "92", date: "Recurring · 2023→", year: "2023→",
      tagline: "Monthly reading group across 14 papers on graph + geometric ML.",
      overview: "Curate a recurring reading group: select papers, write 800-word primers, host live discussions. 14 sessions to date. Average 92 live attendees, 480 newsletter subs.",
      outcomes: ["14 sessions, zero missed", "480 newsletter subscribers", "Featured by Papers With Code"],
      linkedin: "#",
      x: 0.62, y: 0.32,
    },
    {
      id: "e4", name: "Founders' Demo Night", role: "MC + Curator", club: "NIC",
      collaborator: "Antler SEA", speaker: "Panel of 5 founders",
      participants: "180", date: "October 2025", year: "2025",
      tagline: "Curated demo night for 8 graph-native AI startups.",
      overview: "Hosted demo night in collaboration with Antler SEA. Selected 8 startups from 64 applicants, ran the panel, and wrote up a public retrospective.",
      outcomes: ["8 startups demoed", "180 attendees · 60 from VC", "3 startups received term sheets within 30 days"],
      linkedin: "#",
      x: 0.82, y: 0.5,
    },
    {
      id: "e5", name: "Women in AI Mentorship", role: "Mentor + Track Lead", club: "AISG Chapter",
      collaborator: "Women in AI Singapore", speaker: "Dr. Priya Raghavan",
      participants: "60", date: "2024 — 2025", year: "2024",
      tagline: "12-week mentorship program for 30 mentee pairs.",
      overview: "Led the technical track of a 12-week program. Designed the curriculum (vector DBs, agents, retrieval) and 1:1 matched 30 pairs. 92% retention.",
      outcomes: ["30 matched pairs · 92% retention", "12-week curriculum shipped", "4 mentees got their first AI role"],
      linkedin: "#",
      x: 0.32, y: 0.62,
    },
    {
      id: "e6", name: "Open Source Drive", role: "Sprint Captain", club: "OSS-SEA",
      collaborator: "Hugging Face", speaker: "Self-led",
      participants: "210", date: "May 2024", year: "2024",
      tagline: "Weekend sprint contributing to 40 open-source repos.",
      overview: "Captained a weekend sprint where 210 participants opened 412 PRs across 40 OSS repos. Designed the leaderboard, the matching system, and the CI templates.",
      outcomes: ["412 PRs opened · 287 merged", "40 repos touched", "Featured in HF newsletter"],
      linkedin: "#",
      x: 0.55, y: 0.7,
    },
  ],
  edges: [
    ["e1", "e2"], ["e2", "e6"], ["e3", "e1"], ["e1", "e5"], ["e4", "e1"], ["e3", "e6"], ["e5", "e2"], ["e4", "e3"],
  ],
};
